### ISSUE TITLE
User definitions with encrypted passwords does not seem to be idempotent

### ISSUE THREAD

**Issue by grybak-arista** [arista-eosplus/ansible-eos-system#7]
It looks like the encrypted password returned from the running-config has some extra characters inserted in the middle, so the template module thinks the definition does not match. Possibly an issue with the Ansible eos_template module, but it is visible through the ansible-eos-system role.

**Comment by phil-dileo** [comment]
I see issues with any user which includes 'admin' in the name, this also occurs if your user role is network-admin :-)

**Comment by phil-dileo** [comment]
This is a by-product of no_log obfuscating the output.

**Comment by grybak-arista** [comment]
Hmmm... 
The change to using 'show running-config all' seems to have fixed the encrypted password problem, but I will look into the issue with 'admin' in the name or role.

**Comment by grybak-arista** [comment]
Updated the users task to request a clean running-config rather than using the cached _eos_config. Logging from the users task is now explicitly blocked (no_log: true) for security.
